### ISSUE TITLE
Host seafile.example.com not found

### ISSUE THREAD

**Issue by closewall** [piranha771/unraid-templates#2]
I am trying to use this container offline, but I think the nginx .conf file is causing problems.

If I try to download a file from my instance, I get:

> This site can’t be reached
> seafile.example.com’s server IP address could not be found.

Similar thing happens when I use the seafile sync client.

I don't want to run the container through a reverse proxy just yet, and if I do, I'd prefer to use it through my already-existing swag container because it's using my http and https ports.
How do I make sure downloads go through the local domain and not seafile.example.com?

**Comment by piranha771** [comment]
As you have closed the issue, I guess you solved the issue. But thank you for it. I will make the SEAFILE_SERVER_HOSTNAME mandatory for the user to change. I didn't had a problem leaving it as it is but this seems to cause problems.

**Comment by doublemultiply** [comment]
> As you have closed the issue, I guess you solved the issue. But thank you for it. I will make the SEAFILE_SERVER_HOSTNAME mandatory for the user to change. I didn't had a problem leaving it as it is but this seems to cause problems.

Yeah I had to change it from within the Seafile web interface to fix it.
