### ISSUE TITLE
Page not available

### ISSUE THREAD

**Issue by Ghimic** [piranha771/unraid-templates#6]
Hi
Installation and setup went ok . When i try to login , I get this message : 
"Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later."

**Comment by piranha771** [comment]
Please attach startup log of Seafile and MariaDB

**Comment by Ghimic** [comment]
I was putting the wrong SQL password in . Did a fresh install and everything works now

thanks

**Comment by piranha771** [comment]
Ok, closed.
